"""Removed password constraint

Revision ID: 377aecbf9d27
Revises: ef8bd3f1ecb4
Create Date: 2024-04-16 12:28:43.565532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377aecbf9d27'
down_revision = 'ef8bd3f1ecb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
