"""Changed primary key in governor_plowman table

Revision ID: 6a7c2ed5d880
Revises: 644f7af43255
Create Date: 2024-04-23 14:01:11.516694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a7c2ed5d880'
down_revision = '644f7af43255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('governor_plowan',
    sa.Column('plowman_id', sa.Integer(), nullable=False),
    sa.Column('governor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['governor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('plowman_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('governor_plowan')
    # ### end Alembic commands ###
