"""Changed column names

Revision ID: 77628912179e
Revises: c9ef665c9791
Create Date: 2024-04-08 14:38:05.498439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77628912179e'
down_revision = 'c9ef665c9791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postnummer', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('poststed', sa.String(length=255), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('post_place')
        batch_op.drop_column('post_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_number', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('post_place', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('poststed')
        batch_op.drop_column('postnummer')

    # ### end Alembic commands ###
