"""Added order_pending

Revision ID: c4cb16d3cf4e
Revises: 77628912179e
Create Date: 2024-04-08 15:40:43.776041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4cb16d3cf4e'
down_revision = '77628912179e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bestilling', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_pending', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bestilling', schema=None) as batch_op:
        batch_op.drop_column('order_pending')

    # ### end Alembic commands ###
