"""Added relationship tables

Revision ID: ed5b45e32c3e
Revises: 377aecbf9d27
Create Date: 2024-04-22 12:50:02.797988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed5b45e32c3e'
down_revision = '377aecbf9d27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('governor_plowan',
    sa.Column('governor_id', sa.Integer(), nullable=False),
    sa.Column('plowman_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['governor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('governor_id')
    )
    op.create_table('governor_user',
    sa.Column('governor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['governor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('governor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('governor_user')
    op.drop_table('governor_plowan')
    # ### end Alembic commands ###
