"""added tables

Revision ID: fbe563daf138
Revises: 2f0b321e6b44
Create Date: 2024-04-15 10:31:15.927383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe563daf138'
down_revision = '2f0b321e6b44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_customer',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('unit_id')
    )
    op.create_table('unit_sector',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['unit_customer.unit_id'], ),
    sa.PrimaryKeyConstraint('unit_id')
    )
    op.create_table('user_customer',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_customer')
    op.drop_table('unit_sector')
    op.drop_table('unit_customer')
    # ### end Alembic commands ###
