"""changes user_customer table

Revision ID: fbff3cea48d0
Revises: ed5b45e32c3e
Create Date: 2024-04-23 10:25:57.526826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbff3cea48d0'
down_revision = 'ed5b45e32c3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_customer', schema=None) as batch_op:
        # Remove the existing primary key constraint on user_id
        batch_op.drop_constraint('user_customer_pkey', type_='primary')

        # Alter customer_id column to be primary key
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               primary_key=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_customer', schema=None) as batch_op:
        # Remove the primary key constraint on customer_id
        batch_op.drop_constraint('user_customer_pkey', type_='primary')

        # Alter customer_id column to be nullable and remove primary key
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               primary_key=False)

    # ### end Alembic commands ###
